readthedocs/urls.py
# pylint: disable=missing-docstring
import os
from functools import reduce
from operator import add

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView, TemplateView

from readthedocs.core.views import (
    HomepageView,
    SupportView,
    do_not_track,
    server_error_500,
)
from readthedocs.search.views import GlobalSearchView

admin.autodiscover()

handler500 = server_error_500

basic_urls = [
    path("", HomepageView.as_view(), name="homepage"),
    path("security/", TemplateView.as_view(template_name="security.html")),
    re_path(
        r'^\.well-known/security.txt$',
        TemplateView
        .as_view(template_name='security.txt', content_type='text/plain'),
    ),
    path("support/", SupportView.as_view(), name="support"),
    # These are redirected to from the support form
    path(
        "support/success/",
        TemplateView.as_view(template_name="support/success.html"),
        name="support_success",
    ),
    path(
        "support/error/",
        TemplateView.as_view(template_name="support/error.html"),
        name="support_error",
    ),
]

rtd_urls = [
    path("search/", GlobalSearchView.as_view(), name="search"),
    re_path(r"^dashboard/", include("readthedocs.projects.urls.private")),
    re_path(r"^profiles/", include("readthedocs.profiles.urls.public")),
    re_path(r"^accounts/", include("readthedocs.profiles.urls.private")),
    re_path(r"^accounts/", include("allauth.urls")),
    re_path(r"^notifications/", include("readthedocs.notifications.urls")),
    re_path(r"^accounts/gold/", include("readthedocs.gold.urls")),
    path("invitations/", include("readthedocs.invitations.urls")),
    # For redirects
    re_path(r'^builds/', include('readthedocs.builds.urls')),
    # For testing the 500's with DEBUG on.
    path("500/", handler500),
    # Put this as a unique path for the webhook, so we don't clobber existing Stripe URL's
    re_path(r"^djstripe/", include("djstripe.urls", namespace="djstripe")),
]

project_urls = [
    re_path(r'^projects/', include('readthedocs.projects.urls.public')),
]


organization_urls = [
    re_path(
        r'^organizations/',
        include('readthedocs.organizations.urls.private'),
    ),
    re_path(
        r'^organizations/',
        include('readthedocs.organizations.urls.public'),
    ),
    re_path(
        r'^organizations/(?P<slug>[\w.-]+)/subscription/',
        include('readthedocs.subscriptions.urls'),
    ),
    # NOTE: This is overridden in .com to serve a real pricing page.
    path(
        "pricing/",
        RedirectView.as_view(url="https://readthedocs.org/sustainability/"),
        name="pricing",
    ),
]


api_urls = [
    re_path(r'^api/v2/', include('readthedocs.api.v2.urls')),
    # Keep `search_api` at root level, so the test does not fail for other API
    path("api/v2/search/", include("readthedocs.search.api.v2.urls")),
    path("api/v3/search/", include("readthedocs.search.api.v3.urls")),
    # Deprecated
    re_path(r'^api/v1/embed/', include('readthedocs.embed.urls')),
    re_path(r'^api/v2/embed/', include('readthedocs.embed.urls')),
    re_path(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')
    ),
    re_path(r'^api/v3/', include('readthedocs.api.v3.urls')),
    re_path(r'^api/v3/embed/', include('readthedocs.embed.v3.urls')),
]

i18n_urls = [
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

admin_urls = [
    re_path(r'^admin/', admin.site.urls),
]

dnt_urls = [
    re_path(r'^\.well-known/dnt/$', do_not_track),

    # https://github.com/EFForg/dnt-guide#12-how-to-assert-dnt-compliance
    re_path(
        r'^\.well-known/dnt-policy.txt$',
        TemplateView
        .as_view(template_name='dnt-policy.txt', content_type='text/plain'),
    ),
]

debug_urls = []
for build_format in ('epub', 'htmlzip', 'json', 'pdf'):
    debug_urls += static(
        settings.MEDIA_URL + build_format,
        document_root=os.path.join(settings.MEDIA_ROOT, build_format),
    )
debug_urls += [
    path(
        "style-catalog/",
        TemplateView.as_view(template_name="style_catalog.html"),
    ),

    # This must come last after the build output files
    path(
        "media/<path:remainder>",
        RedirectView.as_view(url=settings.STATIC_URL + "%(remainder)s"),
        name="media-redirect",
    ),
]

# Export URLs
groups = [
    basic_urls,
    rtd_urls,
    project_urls,
    organization_urls,
    api_urls,
    i18n_urls,
]

if settings.DO_NOT_TRACK_ENABLED:
    # Include Do Not Track URLs if DNT is supported
    groups.append(dnt_urls)


if settings.READ_THE_DOCS_EXTENSIONS:
    groups.append([
        re_path(r'^', include('readthedocsext.urls'))
    ])

if settings.ALLOW_ADMIN:
    groups.append(admin_urls)

if settings.SHOW_DEBUG_TOOLBAR:
    import debug_toolbar

    debug_urls += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    groups.append(debug_urls)

urlpatterns = reduce(add, groups)

readthedocs/redirects/models.py
"""Django models for the redirects app."""

import re

import structlog
from django.db import models
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from readthedocs.core.resolver import resolve_path
from readthedocs.projects.models import Project

from .querysets import RedirectQuerySet

log = structlog.get_logger(__name__)

HTTP_STATUS_CHOICES = (
    (301, _('301 - Permanent Redirect')),
    (302, _('302 - Temporary Redirect')),
)

STATUS_CHOICES = (
    (True, _('Active')),
    (False, _('Inactive')),
)

TYPE_CHOICES = (
    ('prefix', _('Prefix Redirect')),
    ('page', _('Page Redirect')),
    ('exact', _('Exact Redirect')),
    ('sphinx_html', _('Sphinx HTMLDir -> HTML')),
    ('sphinx_htmldir', _('Sphinx HTML -> HTMLDir')),
    # ('advanced', _('Advanced')),
)

# FIXME: this help_text message should be dynamic since "Absolute path" doesn't
# make sense for "Prefix Redirects" since the from URL is considered after the
# ``/$lang/$version/`` part. Also, there is a feature for the "Exact
# Redirects" that should be mentioned here: the usage of ``$rest``
from_url_helptext = _(
    'Absolute path, excluding the domain. '
    'Example: <b>/docs/</b>  or <b>/install.html</b>',
)
to_url_helptext = _(
    'Absolute or relative URL. Example: '
    '<b>/tutorial/install.html</b>',
)
redirect_type_helptext = _('The type of redirect you wish to use.')


class Redirect(models.Model):

    """A HTTP redirect associated with a Project."""

    project = models.ForeignKey(
        Project,
        verbose_name=_('Project'),
        related_name='redirects',
        on_delete=models.CASCADE,
    )

    redirect_type = models.CharField(
        _('Redirect Type'),
        max_length=255,
        choices=TYPE_CHOICES,
        help_text=redirect_type_helptext,
    )

    from_url = models.CharField(
        _('From URL'),
        max_length=255,
        db_index=True,
        help_text=from_url_helptext,
        blank=True,
    )

    # We are denormalizing the database here to easily query for Exact Redirects
    # with ``$rest`` on them from El Proxito
    from_url_without_rest = models.CharField(
        max_length=255,
        db_index=True,
        help_text='Only for internal querying use',
        blank=True,
        null=True,
    )

    to_url = models.CharField(
        _('To URL'),
        max_length=255,
        db_index=True,
        help_text=to_url_helptext,
        blank=True,
    )
    force = models.BooleanField(
        _("Force redirect"),
        null=True,
        default=False,
        help_text=_("Apply the redirect even if the page exists."),
    )

    http_status = models.SmallIntegerField(
        _('HTTP Status'),
        choices=HTTP_STATUS_CHOICES,
        default=302,
    )
    status = models.BooleanField(choices=STATUS_CHOICES, default=True)

    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)

    objects = RedirectQuerySet.as_manager()

    class Meta:
        verbose_name = _('redirect')
        verbose_name_plural = _('redirects')
        ordering = ('-update_dt',)

    def save(self, *args, **kwargs):  # pylint: disable=arguments-differ
        if self.redirect_type == 'exact' and '$rest' in self.from_url:
            self.from_url_without_rest = self.from_url.replace('$rest', '')
        super().save(*args, **kwargs)

    def __str__(self):
        redirect_text = '{type}: {from_to_url}'
        if self.redirect_type in ['prefix', 'page', 'exact']:
            return redirect_text.format(
                type=self.get_redirect_type_display(),
                from_to_url=self.get_from_to_url_display(),
            )
        return gettext(
            'Redirect: {}'.format(
                self.get_redirect_type_display(),
            ),
        )

    def get_from_to_url_display(self):
        if self.redirect_type in ['prefix', 'page', 'exact']:
            from_url = self.from_url
            to_url = self.to_url
            if self.redirect_type == 'prefix':
                to_url = '/{lang}/{version}/'.format(
                    lang=self.project.language,
                    version=self.project.default_version,
                )
            return '{from_url} -> {to_url}'.format(
                from_url=from_url,
                to_url=to_url,
            )
        return ''

    def get_full_path(self, filename, language=None, version_slug=None, allow_crossdomain=False):
        """
        Return a full path for a given filename.

        This will include version and language information. No protocol/domain
        is returned.
        """
        # Handle explicit http redirects
        if allow_crossdomain and re.match('^https?://', filename):
            return filename

        return resolve_path(
            project=self.project,
            language=language,
            version_slug=version_slug,
            filename=filename,
        )

    def get_redirect_path(self, path, full_path=None, language=None, version_slug=None):
        method = getattr(
            self,
            'redirect_{type}'.format(
                type=self.redirect_type,
            ),
        )
        return method(
            path, full_path=full_path, language=language, version_slug=version_slug
        )

    def redirect_prefix(self, path, full_path, language=None, version_slug=None):
        if path.startswith(self.from_url):
            log.debug("Redirecting...", redirect=self)
            # pep8 and blank don't agree on having a space before :.
            cut_path = path[len(self.from_url) :]  # noqa

            to = self.get_full_path(
                filename=cut_path,
                language=language,
                version_slug=version_slug,
                allow_crossdomain=False,
            )
            return to

    def redirect_page(self, path, full_path, language=None, version_slug=None):
        if path == self.from_url:
            log.debug('Redirecting...', redirect=self)
            to = self.get_full_path(
                filename=self.to_url.lstrip('/'),
                language=language,
                version_slug=version_slug,
                allow_crossdomain=True,
            )
            return to

    def redirect_exact(self, path, full_path, language=None, version_slug=None):
        if full_path == self.from_url:
            log.debug('Redirecting...', redirect=self)
            return self.to_url
        # Handle full sub-level redirects
        if '$rest' in self.from_url:
            match = self.from_url.split('$rest')[0]
            if full_path.startswith(match):
                cut_path = full_path.replace(match, self.to_url, 1)
                return cut_path

    def redirect_sphinx_html(self, path, full_path, language=None, version_slug=None):
        for ending in ['/', '/index.html']:
            if path.endswith(ending):
                log.debug('Redirecting...', redirect=self)
                path = path[1:]  # Strip leading slash.
                to = re.sub(ending + '$', '.html', path)
                return self.get_full_path(
                    filename=to,
                    language=language,
                    version_slug=version_slug,
                    allow_crossdomain=False,
                )

    def redirect_sphinx_htmldir(
        self, path, full_path, language=None, version_slug=None
    ):
        if path.endswith(".html"):
            log.debug("Redirecting...", redirect=self)
            path = path[1:]  # Strip leading slash.
            to = re.sub('.html$', '/', path)
            return self.get_full_path(
                filename=to,
                language=language,
                version_slug=version_slug,
                allow_crossdomain=False,
            )

readthedocs/redirects/templates/redirects/redirect_form.html
{% extends "projects/project_edit_base.html" %}

{% load i18n %}

{% block title %}{% trans "Redirect" %}{% endblock %}

{% block project-redirects-active %}active{% endblock %}
{% block project_edit_content_header %}{% trans "Redirects" %}{% endblock %}

{% block extra_scripts %}
    <script type="text/javascript">

        var update_outcome = function() {
            $('#id_from_url').parent().hide()
            $('#id_to_url').parent().hide()
            $('#dynamic-redirect').hide()

            let redirect_type = $('#id_redirect_type').val();
            if (redirect_type == 'prefix') {
                $('#id_from_url').parent().show()
                $('#id_to_url').parent().hide()
            }
            else if (redirect_type == 'page') {
                $('#id_from_url').parent().show()
                $('#id_to_url').parent().show()
            }
            else if (redirect_type == 'exact') {
                $('#id_from_url').parent().show()
                $('#id_to_url').parent().show()
            }

            var field_from_url = $('#id_from_url');
                field_to_url =  $('#id_to_url');
                option = $('#id_redirect_type').val();
                redirect_from = "";
                redirect_target = "";

            if (option === "prefix") {
                redirect_from = field_from_url.val() + "faq.html";
                redirect_target = "/$lang/$version/faq.html";
            }
            else if (option === "page" ) {
                redirect_from = "/$lang/$version/" + field_from_url.val().replace(/^\/+/, '');
                redirect_target = "/$lang/$version/" + field_to_url.val().replace(/^\/+/, '');
            }
            else if (option === "exact" ) {
                redirect_from =  field_from_url.val();
                redirect_target =  field_to_url.val();
            }

            if (redirect_from && redirect_target) {
                var result = "Outcome: " + redirect_from + " -> " + redirect_target;
                $('#dynamic-redirect').text(result).show();
            } else {
                $('#dynamic-redirect').text("").hide();
            }
        };

        $(document).ready(function() {
            update_outcome();
            $('#id_redirect_type').bind('change', function(ev) {
                update_outcome();
            });
            $('#id_from_url, #id_to_url').keyup(update_outcome);
        });

    </script>
{% endblock %}

{% block project_edit_content %}
  <p class="help_text">
    {% blocktrans trimmed with docs_url='https://docs.readthedocs.io/page/user-defined-redirects.html' %}
        Add redirects for your project. This allows you to fix links to old pages that are 404ing. <a href="{{ docs_url }}">Learn more</a>.
    {% endblocktrans %}
  </p>

  <form method="post" action=".">{% csrf_token %}
    {{ form.as_p }}
    <div id="dynamic-redirect" class="empty"></div>
    <input type="submit" value="{% trans "Save" %}">
  </form>

  {% if redirect %}
    <form
        method="post"
        action="{% url 'projects_redirects_delete' project_slug=project.slug redirect_pk=redirect.pk %}">
      {% csrf_token %}
      <input type="submit" value="{% trans "Delete" %}">
    </form>
  {% endif %}
{% endblock %}

readthedocs/redirects/templates/redirects/redirect_list.html
{% extends "projects/project_edit_base.html" %}

{% load i18n %}

{% block title %}{% trans "Redirects" %}{% endblock %}

{% block project-redirects-active %}active{% endblock %}
{% block project_edit_content_header %}{% trans "Redirects" %}{% endblock %}

{% block project_edit_content %}
  <p class="help_text">
    {% blocktrans trimmed with docs_url='https://docs.readthedocs.io/page/user-defined-redirects.html' %}
        Add redirects for your project. This allows you to fix links to old pages that are 404ing. <a href="{{ docs_url }}">Learn more</a>.
    {% endblocktrans %}
  </p>

  <div class="button-bar">
    <ul>
      <li>
        <a class="button"
           href="{% url 'projects_redirects_create' project_slug=project.slug %}">
          {% trans "Add Redirect" %}
        </a>
      </li>
    </ul>
  </div>

  <div class="module">
    <div class="module-list">
      <div class="module-list-wrapper">
        <ul>
          {% for redirect in redirects %}
            <li class="module-item">
              <div>
                {{ redirect.get_redirect_type_display }}
              </div>
              {% if redirect.get_from_to_url_display %}
                <div>
                  {{ redirect.get_from_to_url_display }}
                </div>
              {% endif %}
              <ul class="module-item-menu">
                <li>
                  <a href="{% url 'projects_redirects_edit' project_slug=project.slug redirect_pk=redirect.pk %}">
                    {% trans "Edit" %}
                  </a>
                </li>
              </ul>
            </li>
          {% empty %}
            <li class="module-item">
              <p class="quiet">
                {% trans "No redirects found." %}
              </p>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}